title: damageboy
email: dans@houmus.org
description: >- 
  damageboy's place to vent over those mean computers
baseurl:
url: https://bits.houmus.org
incremental: true
show_dir_listing: false
search: true
search_provider: algolia
twitter_username: damageboy
github_username: damageboy
repository: "damageboy/damageboy.github.io"
words_per_minute: 200
minimal_mistakes_skin: air #"aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
google_site_verification: "wcrvaF3e88-Vb6y-9eUTqYaXDMOukzl4c-IdKByS0Xc"
bing_site_verification: "6D5AE23298671D95A20FAD7FA3430ABB"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.16.6
# Outputting
permalink: /:year-:month-:day/:title
breadcrumbs: true
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: UTC

# Reading Files
include:
  - .htaccess
  - _posts
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
encoding: "utf-8"

# Plugins (previously gems:)
plugins:
  - jekyll-relative-links
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-github-metadata

author:
  name         : "damageboy"
  avatar       : "/assets/images/atari.svg"
  bio          : "What did I do this time?"
  email        : "dans@houmus.org"
  uri          : "https://bits.houmus.org"
  stackoverflow: "9172/damageboy"
  twitter      : "damageboy"

comments:
  provider: "disqus"
  disqus:
    shortname: "damageboy-github-io"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-124434205-1"
    anonymize_ip: false # default

relative_links:
  enabled: true
  collections: true

algolia:
  application_id: CMJJV3VL7A
  index_name: bits.houmus.org
  search_only_api_key: f1673463105fd4295fbbeffc415b5934
  powered_by: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

head_scripts:
 - //ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js
 - /assets/scripts/inlineDisqussions.js
 - //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML


footer_scripts:
 - /assets/scripts/applyInlineDisqussions.js
