title: damageboy
email: dans@houmus.org
description: >- 
  damageboy's place to vent over those mean computers
incremental: true
baseurl:
url: https://bits.houmus.org
show_dir_listing: false
search: true
search_provider: algolia
twitter_username: damageboy
github_username: damageboy
repository: "damageboy/damageboy.github.io"
words_per_minute: 100
minimal_mistakes_skin: air #"aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
google_site_verification: "wcrvaF3e88-Vb6y-9eUTqYaXDMOukzl4c-IdKByS0Xc"
bing_site_verification: "6D5AE23298671D95A20FAD7FA3430ABB"

# Local serving
host: 0.0.0.0

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.17.2

# Outputting
permalink: /:year-:month-:day/:title
breadcrumbs: false
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: UTC
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Reading Files
include:
  - .htaccess
  - _posts
  - _pages
exclude:
  - talks/*/*.md
  - "*.sublime-project"
  - "*.sublime-workspace"
  - gems
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README.md
  - tmp
  - tests
keep_files:
  - .git
encoding: "utf-8"

# Plugins (previously gems:)
plugins:
  - jekyll-relative-links
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-code-tabs

author:
  name         : "damageboy"
  avatar       : "/assets/images/atari.svg"
  bio          : "What did I do this time?"
  email        : "dans@houmus.org"
  uri          : "https://bits.houmus.org"
  stackoverflow: "9172/damageboy"
  twitter      : "damageboy"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-124434205-1"
    anonymize_ip: false # default

relative_links:
  enabled: true
  collections: true

algolia:
  application_id: CMJJV3VL7A
  index_name: bits.houmus.org
  search_only_api_key: f1673463105fd4295fbbeffc415b5934
  powered_by: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
 # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      comments: false
      read_time: false
