name: Build

on: 
  push:
    branches:
      - dev

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: install bundles
        shell: bash
        run: bundle install

      - name: build with jekyll
        shell: bash
        run: bundle exec jekyll build